name: Wheels

on:
  push:
    branches:
      - master
      - stable
      - docs
      - actions*
    tags:
      - v*
  workflow_dispatch:

jobs:
  crate:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
          
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            submodules: recursive
  
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
          
        - name: Setup CMake
          uses: jwlawson/actions-setup-cmake@v2.0
       
        #- name: Setup Ninja              
        #  uses: ashutoshvarma/setup-ninja@v1.1
  
        - name: Install requirements
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install --upgrade build

        #- name: Install LLVM and Clang
          #uses: KyleMayes/install-llvm-action@v2
          #with:
            #version: "10.0"
    
        #- name: build
          #env:
           # CXX: clang++
          #run: |
           # make
            
        - name: Set deployment target (macOS)
          run: echo "MACOSX_DEPLOYMENT_TARGET=14.0" >> $GITHUB_ENV 
          if: matrix.os == 'macos-latest'
  
        - name: Build wheel
          env:
              CMAKE_GENERATOR: "MinGW Makefiles"
          run: |
            python3 -m build --wheel --outdir dist
          
        - name: Upload binary
          uses: actions/upload-artifact@v4
          with:
            name: wheel-${{ matrix.os }}
            path: dist/*.whl

        - name: Commit and push
          run: |
            git pull
            git config user.email "meowmeowmeow@gmail.com"
            git config user.name "meowmeowmeow"
            git add dist
            git commit -m "Generated distributions"
            git push
  
        - name: Install and import ecl
          run: |
            python3 -m pip install --no-index --find-links=dist ecl
            python3 -c 'import ecl'
